# Generated by Django 5.1.6 on 2025-03-07 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStacks',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_pic', models.ImageField(default='C:\\Users\\singh\\Desktop\\Codes\\django\\freelance-market\\marketplace\\media\\profilepics\\default\\avatar.png', max_length=600, upload_to='profilepics/')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField()),
                ('md_content', models.FileField(max_length=1000, upload_to='job_description/')),
                ('profession_type', models.CharField(choices=[('JOBS', 'JOBS'), ('INTERNSHIP', 'INTERNSHIP'), ('FREELANCE', 'FREELANCE')])),
                ('salary', models.BigIntegerField()),
                ('experience', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.recruiter')),
                ('techstack', models.ManyToManyField(to='recruiters.techstacks')),
            ],
        ),
    ]
