# Generated by Django 5.1.6 on 2025-03-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='profile_pic',
            field=models.ImageField(default='profilepics\\default\\avatar.png', max_length=600, upload_to='profilepics/'),
        ),
    ]
