# Generated by Django 5.1.6 on 2025-03-09 07:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_alter_recruiter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='md_content',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
