# Generated by Django 5.1.6 on 2025-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_alter_recruiter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professions',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professions',
            name='profession_type',
            field=models.CharField(choices=[('JOBS', 'JOBS'), ('INTERNSHIP', 'INTERNSHIP'), ('FREELANCE', 'FREELANCE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='techstacks',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
