# Generated by Django 5.1.6 on 2025-03-07 08:02

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('profile_pic', models.ImageField(default='C:\\Users\\singh\\Desktop\\Codes\\django\\freelance-market\\marketplace\\media\\profilepics\\default\\avatar.png', upload_to='profilepics/')),
                ('experiences', models.JSONField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('md_content', models.FileField(upload_to='md_content/')),
                ('resume', models.FileField(default='C:\\Users\\singh\\Desktop\\Codes\\django\\freelance-market\\marketplace\\media\\resumes\\default\\f1.md', upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('tech_stack', models.ManyToManyField(blank=True, to='recruiters.techstacks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.professions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'profession')},
            },
        ),
        migrations.CreateModel(
            name='UserJobApplication',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('get_hired', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.professions')),
            ],
            options={
                'unique_together': {('profession', 'candidate')},
            },
        ),
    ]
