# Generated by Django 5.1.6 on 2025-03-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='profile_pic',
            field=models.ImageField(default='profilepics\\default\\avatar.png', upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(default='resumes\\default\\f1.md', upload_to='resumes/'),
        ),
    ]
