# Generated by Django 5.1.6 on 2025-03-09 07:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidates_profile_pic_alter_candidates_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='md_content',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
