# Generated by Django 5.1.6 on 2025-03-09 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidates_md_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
