# Generated by Django 5.1.6 on 2025-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidates_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
